name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST 'echo SSH connection successful'
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          # pip install -r requirements.txt

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "mkdir -p /root/repos/askgbt"
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" . $SERVER_USER@$SERVER_HOST:/root/repos/askgbt

      - name: Restart application on server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
            cd /root/repos/askgbt
            python3 -m venv venv
            source venv/bin/activate
            # pip install -r requirements.txt
            pkill -f main.py || true
            nohup python3 main.py &
          EOF
